//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableEventsInConstructors")]
        public ChequeTable()
        {
            this.MenuTable = new HashSet<MenuTable>();
        }
    
        public int PersonalNumber_Cheque { get; set; }
        public Nullable<System.DateTime> DataTime_Cheque { get; set; }
        public string pnCash_Cheque { get; set; }
        public Nullable<int> pnWorker_Cheque { get; set; }
    
        public virtual WorkerTable WorkerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuTable> MenuTable { get; set; }
    }
}
