//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalBookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalBookTable()
        {
            this.WorkerTabe = new HashSet<WorkerTabe>();
        }
    
        public int PersonalNumber_MedicalBook { get; set; }
        public string Issue_MedicalBook { get; set; }
        public string SNMDirector_MedicalBook { get; set; }
        public System.DateTime DateIssue_MedicalBook { get; set; }
        public string HomeAdress_MedicalBook { get; set; }
        public string Role_MedicalBook { get; set; }
        public string Organization_MedicalBook { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerTabe> WorkerTabe { get; set; }
    }
}
