//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTM_ChequeMenu
    {
        public int pnCheque { get; set; }
        public int pnMenu { get; set; }
        public int Quantity_MenuCheque { get; set; }
    
        public virtual ChequeTable ChequeTable { get; set; }
        public virtual MenuTable MenuTable { get; set; }
    }
}
