//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassportTable()
        {
            this.WorkerTable = new HashSet<WorkerTable>();
        }
    
        public string Series_Passport { get; set; }
        public string Number_Passport { get; set; }
        public string Surname_Passport { get; set; }
        public string Name_Passport { get; set; }
        public string Middlename_Passport { get; set; }
        public int pnGender_Passport { get; set; }
        public System.DateTime DateOfBrich_Passport { get; set; }
        public string LocationOfBrich_Passport { get; set; }
        public string Issued_Passport { get; set; }
        public System.DateTime DateIssued_Passport { get; set; }
        public string DivisionCode_Passport { get; set; }
        public string pnImage_Passport { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        public virtual ImagePassportTable ImagePassportTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerTable> WorkerTable { get; set; }
    }
}
