//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceResidenceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableEventsInConstructors")]
        public PlaceResidenceTable()
        {
            this.WorkerTable = new HashSet<WorkerTable>();
        }
    
        public string PersonalNumber_PlaceResidence { get; set; }
        public System.DateTime RegistrationDate_PlaceResidence { get; set; }
        public string Region_PlaceResidence { get; set; }
        public string District_PlaceResidence { get; set; }
        public string Point_PlaceResidence { get; set; }
        public string Street_PlaceResidence { get; set; }
        public string House_PlaceResidence { get; set; }
        public string Flat_PlaceResidence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerTable> WorkerTable { get; set; }
    }
}
