//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMenuCategory
    {
        public string Title_MenuCategory { get; set; }
        public Nullable<decimal> MinPrise_ViewMenuCategory { get; set; }
        public Nullable<decimal> MaxPrise_ViewMenuCategory { get; set; }
        public Nullable<decimal> AvgPrise_ViewMenuCategory { get; set; }
        public Nullable<int> Count_ViewMenuCategory { get; set; }
    }
}
