//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesctopHITE.AppDateFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerTabe
    {
        public int PersonalNumber_Worker { get; set; }
        public string Phone_Worker { get; set; }
        public string Login_Worker { get; set; }
        public string Email_Worker { get; set; }
        public string Password_Worker { get; set; }
        public int pnRole_Worker { get; set; }
        public string SeriesPassport_Worker { get; set; }
        public string NumberPassport_Worker { get; set; }
        public string pnPlaceResidence_Worker { get; set; }
        public int pnMedicalBook_Worker { get; set; }
        public string pnSalaryCard_Worker { get; set; }
        public System.DateTime DateWord_Worker { get; set; }
        public int pnStatus_Worker { get; set; }
        public string pnINN_Worker { get; set; }
        public string pnSnils_Worker { get; set; }
    
        public virtual INNTable INNTable { get; set; }
        public virtual MedicalBookTable MedicalBookTable { get; set; }
        public virtual PassportTable PassportTable { get; set; }
        public virtual PlaceResidenceTable PlaceResidenceTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual SalaryCardTable SalaryCardTable { get; set; }
        public virtual SnilsTable SnilsTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
